template <typename T>
struct value_storage {
	T value;
	bool initialized = false;
};

template <typename T, size_t max_count>
struct value_array_storage {
	std::array<T, max_count> values;
	bool initialized = false;
};

struct trailer_data {
	value_storage<scs_value_bool_t> trailer_channel_connected;
	value_storage<scs_value_float_t> trailer_channel_cargo_damage;
	value_storage<scs_value_dplacement_t> trailer_channel_world_placement;
	value_storage<scs_value_fvector_t> trailer_channel_local_linear_velocity;
	value_storage<scs_value_fvector_t> trailer_channel_local_angular_velocity;
	value_storage<scs_value_fvector_t> trailer_channel_local_linear_acceleration;
	value_storage<scs_value_fvector_t> trailer_channel_local_angular_acceleration;
	value_storage<scs_value_float_t> trailer_channel_wear_body;
	value_storage<scs_value_float_t> trailer_channel_wear_chassis;
	value_storage<scs_value_float_t> trailer_channel_wear_wheels;
	value_array_storage<scs_value_float_t, 19> trailer_channel_wheel_susp_deflection;
	value_array_storage<scs_value_bool_t, 19> trailer_channel_wheel_on_ground;
	value_array_storage<scs_value_u32_t, 19> trailer_channel_wheel_substance;
	value_array_storage<scs_value_float_t, 19> trailer_channel_wheel_velocity;
	value_array_storage<scs_value_float_t, 19> trailer_channel_wheel_steering;
	value_array_storage<scs_value_float_t, 19> trailer_channel_wheel_rotation;
	value_array_storage<scs_value_float_t, 19> trailer_channel_wheel_lift;
	value_array_storage<scs_value_float_t, 19> trailer_channel_wheel_lift_offset;
};

struct game_data_store{
	value_storage<scs_value_float_t> channel_local_scale;
	value_storage<scs_value_u32_t> channel_game_time;
	value_storage<scs_value_s32_t> channel_multiplayer_time_offset;
	value_storage<scs_value_s32_t> channel_next_rest_stop;
	value_storage<scs_value_float_t> job_channel_cargo_damage;
	value_storage<scs_value_dplacement_t> truck_channel_world_placement;
	value_storage<scs_value_fvector_t> truck_channel_local_linear_velocity;
	value_storage<scs_value_fvector_t> truck_channel_local_angular_velocity;
	value_storage<scs_value_fvector_t> truck_channel_local_linear_acceleration;
	value_storage<scs_value_fvector_t> truck_channel_local_angular_acceleration;
	value_storage<scs_value_fplacement_t> truck_channel_cabin_offset;
	value_storage<scs_value_fvector_t> truck_channel_cabin_angular_velocity;
	value_storage<scs_value_fvector_t> truck_channel_cabin_angular_acceleration;
	value_storage<scs_value_fplacement_t> truck_channel_head_offset;
	value_storage<scs_value_float_t> truck_channel_speed;
	value_storage<scs_value_float_t> truck_channel_engine_rpm;
	value_storage<scs_value_s32_t> truck_channel_engine_gear;
	value_storage<scs_value_s32_t> truck_channel_displayed_gear;
	value_storage<scs_value_float_t> truck_channel_input_steering;
	value_storage<scs_value_float_t> truck_channel_input_throttle;
	value_storage<scs_value_float_t> truck_channel_input_brake;
	value_storage<scs_value_float_t> truck_channel_input_clutch;
	value_storage<scs_value_float_t> truck_channel_effective_steering;
	value_storage<scs_value_float_t> truck_channel_effective_throttle;
	value_storage<scs_value_float_t> truck_channel_effective_brake;
	value_storage<scs_value_float_t> truck_channel_effective_clutch;
	value_storage<scs_value_float_t> truck_channel_cruise_control;
	value_storage<scs_value_u32_t> truck_channel_hshifter_slot;
	value_array_storage<scs_value_bool_t, 2> truck_channel_hshifter_selector;
	value_storage<scs_value_bool_t> truck_channel_parking_brake;
	value_storage<scs_value_bool_t> truck_channel_motor_brake;
	value_storage<scs_value_u32_t> truck_channel_retarder_level;
	value_storage<scs_value_float_t> truck_channel_brake_air_pressure;
	value_storage<scs_value_bool_t> truck_channel_brake_air_pressure_warning;
	value_storage<scs_value_bool_t> truck_channel_brake_air_pressure_emergency;
	value_storage<scs_value_float_t> truck_channel_brake_temperature;
	value_storage<scs_value_float_t> truck_channel_fuel;
	value_storage<scs_value_bool_t> truck_channel_fuel_warning;
	value_storage<scs_value_float_t> truck_channel_fuel_average_consumption;
	value_storage<scs_value_float_t> truck_channel_fuel_range;
	value_storage<scs_value_float_t> truck_channel_adblue;
	value_storage<scs_value_bool_t> truck_channel_adblue_warning;
	value_storage<scs_value_float_t> truck_channel_adblue_average_consumption;
	value_storage<scs_value_float_t> truck_channel_oil_pressure;
	value_storage<scs_value_bool_t> truck_channel_oil_pressure_warning;
	value_storage<scs_value_float_t> truck_channel_oil_temperature;
	value_storage<scs_value_float_t> truck_channel_water_temperature;
	value_storage<scs_value_bool_t> truck_channel_water_temperature_warning;
	value_storage<scs_value_float_t> truck_channel_battery_voltage;
	value_storage<scs_value_bool_t> truck_channel_battery_voltage_warning;
	value_storage<scs_value_bool_t> truck_channel_electric_enabled;
	value_storage<scs_value_bool_t> truck_channel_engine_enabled;
	value_storage<scs_value_bool_t> truck_channel_lblinker;
	value_storage<scs_value_bool_t> truck_channel_rblinker;
	value_storage<scs_value_bool_t> truck_channel_hazard_warning;
	value_storage<scs_value_bool_t> truck_channel_light_lblinker;
	value_storage<scs_value_bool_t> truck_channel_light_rblinker;
	value_storage<scs_value_bool_t> truck_channel_light_parking;
	value_storage<scs_value_bool_t> truck_channel_light_low_beam;
	value_storage<scs_value_bool_t> truck_channel_light_high_beam;
	value_storage<scs_value_u32_t> truck_channel_light_aux_front;
	value_storage<scs_value_u32_t> truck_channel_light_aux_roof;
	value_storage<scs_value_bool_t> truck_channel_light_beacon;
	value_storage<scs_value_bool_t> truck_channel_light_brake;
	value_storage<scs_value_bool_t> truck_channel_light_reverse;
	value_storage<scs_value_bool_t> truck_channel_wipers;
	value_storage<scs_value_float_t> truck_channel_dashboard_backlight;
	value_storage<scs_value_bool_t> truck_channel_differential_lock;
	value_storage<scs_value_bool_t> truck_channel_lift_axle;
	value_storage<scs_value_bool_t> truck_channel_lift_axle_indicator;
	value_storage<scs_value_bool_t> truck_channel_trailer_lift_axle;
	value_storage<scs_value_bool_t> truck_channel_trailer_lift_axle_indicator;
	value_storage<scs_value_float_t> truck_channel_wear_engine;
	value_storage<scs_value_float_t> truck_channel_wear_transmission;
	value_storage<scs_value_float_t> truck_channel_wear_cabin;
	value_storage<scs_value_float_t> truck_channel_wear_chassis;
	value_storage<scs_value_float_t> truck_channel_wear_wheels;
	value_storage<scs_value_float_t> truck_channel_odometer;
	value_storage<scs_value_float_t> truck_channel_navigation_distance;
	value_storage<scs_value_float_t> truck_channel_navigation_time;
	value_storage<scs_value_float_t> truck_channel_navigation_speed_limit;
	value_array_storage<scs_value_float_t, 14> truck_channel_wheel_susp_deflection;
	value_array_storage<scs_value_bool_t, 14> truck_channel_wheel_on_ground;
	value_array_storage<scs_value_u32_t, 14> truck_channel_wheel_substance;
	value_array_storage<scs_value_float_t, 14> truck_channel_wheel_velocity;
	value_array_storage<scs_value_float_t, 14> truck_channel_wheel_steering;
	value_array_storage<scs_value_float_t, 14> truck_channel_wheel_rotation;
	value_array_storage<scs_value_float_t, 14> truck_channel_wheel_lift;
	value_array_storage<scs_value_float_t, 14> truck_channel_wheel_lift_offset;
	trailer_data trailers;
};

